#******* Definitely do not use this setup in production! ******* 
#Simple single broker example using only for local development
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    
    environment:
      #Not for production
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:latest
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=0
      - ZOOKEEPER=zookeeper:2181

      #Not for production
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes

  producer:
    depends_on:
      - kafka
    environment:
      - TOPIC=example-topic
      - ENVIRONMENT=local
      - INTERNAL_KAFKA_ADDR=kafka:9091
    build:
      context: ./Producer

  consumer:
    depends_on:
      - kafka
    environment:
      - TOPIC=example-topic
      - ENVIRONMENT=local
      - INTERNAL_KAFKA_ADDR=kafka:9091
    build:
      context: ./Consumer
volumes: {}