consumer:
    build: .
    command: bash -c "sleep 6 && /kafka/bin/kafka-console-consumer.sh --topic dates --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092"
    depends_on:
    - zookeeper
    - kafka1
    - kafka2
    - kafka3