version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"

    #For a production app Need to change this to some sort of auth (jwt?)
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

#Update these to persistent storage if necessary
volumes:
  zookeeper_data:
    driver: local
